/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import mail.Mail;

/**
 *
 * @author HereIAm
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        
        initComponents();
    }
    
    File file = null;
    
    public void action()
    {
       //String var =  textComplain.getSelectedText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textComplain = new javax.swing.JTextArea();
        buttonSend = new javax.swing.JButton();
        buttonAttachment = new javax.swing.JButton();
        labelImageName = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Complaint Form ");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Explanation Of Complaint");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 150, 210);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 150, 30);

        textAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(textAddress);
        textAddress.setBounds(180, 150, 340, 30);

        textName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(textName);
        textName.setBounds(180, 70, 200, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone No.");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 150, 30);

        textPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(textPhone);
        textPhone.setBounds(180, 110, 200, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Address");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 150, 30);

        textComplain.setColumns(20);
        textComplain.setRows(5);
        jScrollPane2.setViewportView(textComplain);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 190, 340, 210);

        buttonSend.setText("Send");
        buttonSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSend.setFocusPainted(false);
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSend);
        buttonSend.setBounds(30, 410, 150, 30);

        buttonAttachment.setText("Attach Image");
        buttonAttachment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonAttachment.setFocusPainted(false);
        buttonAttachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAttachmentActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAttachment);
        buttonAttachment.setBounds(390, 70, 130, 30);

        labelImageName.setBackground(new java.awt.Color(255, 255, 255));
        labelImageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImageName.setText("   No Image Added !");
        labelImageName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(labelImageName);
        labelImageName.setBounds(390, 110, 130, 30);
        getContentPane().add(canvas1);
        canvas1.setBounds(230, 220, 20, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
               // TODO add your handling code here:
        buttonSend.setName("Sending . . .");
        
        
        String subject = "Complain By "+ textName.getText() ;
        String body = textName.getText() + "\n\n" + textPhone.getText() + "\n"+ textAddress.getText() + "\n\n" +  textComplain.getText() + "\n\n"  ;
        
        Mail mail = new Mail();
        mail.send("*****@gmail.com", "***pass****", "crack6901@gmail.com", subject ,body ,file);
        
        
        buttonSend.setName("Sent");
        file = null;
        labelImageName.setText("No Image Added !");
        buttonSend.setName("Send");
    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonAttachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAttachmentActionPerformed
        // TODO add your handling code here:
        JFileChooser jch=new JFileChooser();
        //jch.setFileSelectionMode(JFileChooser.);
        jch.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        jch.setCurrentDirectory(new java.io.File(""));
        jch.showOpenDialog(this);
        file = jch.getSelectedFile();
        if (null!= jch.getSelectedFile())
        {
            System.out.print(jch.getSelectedFile().getName());
            labelImageName.setText(jch.getSelectedFile().getName());
        }
        
        //mail.sendMail(jch.getSelectedFile());
    }//GEN-LAST:event_buttonAttachmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAttachment;
    private javax.swing.JButton buttonSend;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImageName;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextArea textComplain;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables
}
